# Generated by Django 5.1.5 on 2026-06-15 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("age", models.PositiveSmallIntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("weight_kg", models.FloatField()),
                ("height_cm", models.FloatField()),
                ("activity_multiplier", models.FloatField(default=1.2)),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("lose", "Lose weight"),
                            ("maintain", "Maintain"),
                            ("gain_muscle", "Gain muscle"),
                            ("gain_weight", "Gain weight"),
                        ],
                        default="maintain",
                        max_length=20,
                    ),
                ),
                ("goal_offset_kcal", models.IntegerField(default=0)),
                ("bmi", models.FloatField()),
                ("bmr", models.IntegerField()),
                ("tdee", models.IntegerField()),
                ("target_kcal", models.IntegerField()),
                ("protein_target_g", models.IntegerField()),
                ("carb_target_g", models.IntegerField()),
                ("fat_target_g", models.IntegerField()),
                ("is_current", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_current"],
                        name="metrics_met_user_id_ed27e9_idx",
                    )
                ],
            },
        ),
    ]
