# Generated by Django 5.1.5 on 2026-06-22 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmr', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active'), ('extremely_active', 'Extremely Active')], max_length=30)),
                ('activity_multiplier', models.DecimalField(decimal_places=3, max_digits=4)),
                ('tdee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'body_metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', '-recorded_at'], name='body_metric_user_id_1e9e12_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('maintain_weight', 'Maintain Weight'), ('gain_muscle', 'Gain Muscle')], max_length=20)),
                ('calorie_offset', models.SmallIntegerField(default=0)),
                ('target_calories', models.PositiveSmallIntegerField()),
                ('target_protein_g', models.PositiveSmallIntegerField()),
                ('target_carbs_g', models.PositiveSmallIntegerField()),
                ('target_fat_g', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_goals',
                'indexes': [models.Index(fields=['user', 'is_active'], name='health_goal_user_id_dcde6b_idx')],
            },
        ),
    ]
