# Generated by Django 5.1.5 on 2026-06-22 09:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        ('metrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(default='My meal plan', max_length=100)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal_plans',
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=50)),
                ('model_version', models.CharField(max_length=20)),
                ('algorithm', models.CharField(choices=[('KNN', 'KNN'), ('RandomForest', 'RandomForest'), ('Ensemble', 'Ensemble')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('feature_list', models.JSONField(blank=True, null=True)),
                ('hyperparameters', models.JSONField(blank=True, null=True)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('f1_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('model_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ml_models',
                'indexes': [models.Index(fields=['model_name', 'is_active'], name='ml_models_model_n_34f2ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('knn_neighbours_used', models.PositiveSmallIntegerField(default=5)),
                ('total_foods_scored', models.PositiveSmallIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('body_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.bodymetric')),
                ('health_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.healthgoal')),
                ('knn_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recommendations.mlmodel')),
                ('rf_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recommendations.mlmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('rank_position', models.PositiveSmallIntegerField()),
                ('rf_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('knn_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ensemble_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('serving_g', models.PositiveSmallIntegerField()),
                ('estimated_kcal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estimated_protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bowen_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.bowenfood')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.recommendation')),
            ],
            options={
                'db_table': 'recommendation_items',
            },
        ),
        migrations.CreateModel(
            name='MealPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('serving_g', models.PositiveSmallIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('bowen_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.bowenfood')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.mealplan')),
                ('recommendation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.recommendationitem')),
            ],
            options={
                'db_table': 'meal_plan_items',
            },
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'day_of_week'], name='meal_plans_user_id_c9c2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', '-generated_at'], name='recommendat_user_id_e74f03_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationitem',
            index=models.Index(fields=['recommendation', 'meal_time', 'rank_position'], name='recommendat_recomme_d1b88d_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationitem',
            index=models.Index(fields=['bowen_food'], name='recommendat_bowen_f_d9e729_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplanitem',
            index=models.Index(fields=['plan', 'meal_time'], name='meal_plan_i_plan_id_ccacc9_idx'),
        ),
    ]
