# Generated by Django 5.1.5 on 2026-06-22 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nfct_code', models.CharField(max_length=20, unique=True)),
                ('food_name', models.CharField(max_length=150)),
                ('local_name', models.CharField(blank=True, max_length=150, null=True)),
                ('food_category', models.CharField(db_index=True, max_length=80)),
                ('energy_kcal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('carbohydrate_g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fibre_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sugar_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('iron_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calcium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vitamin_c_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('vitamin_a_ug', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_high_protein', models.BooleanField(default=False)),
                ('is_high_fibre', models.BooleanField(default=False)),
                ('is_low_calorie', models.BooleanField(default=False)),
                ('nfct_edition', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'food_items',
                'indexes': [models.Index(fields=['food_category'], name='food_items_food_ca_68fb7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='BowenFood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=150)),
                ('food_category', models.CharField(db_index=True, max_length=80)),
                ('meal_time', models.CharField(default='lunch,dinner', max_length=100)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('contains_gluten', models.BooleanField(default=False)),
                ('contains_nuts', models.BooleanField(default=False)),
                ('contains_pork', models.BooleanField(default=False)),
                ('contains_fish', models.BooleanField(default=False)),
                ('contains_lactose', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('availability_note', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nfct_food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowen_foods', to='foods.fooditem')),
            ],
            options={
                'db_table': 'bowen_foods',
                'indexes': [models.Index(fields=['food_category'], name='bowen_foods_food_ca_c12393_idx'), models.Index(fields=['is_available'], name='bowen_foods_is_avai_217259_idx')],
            },
        ),
    ]
