# Generated by Django 5.1.5 on 2026-06-15 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DietaryTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=60)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(db_index=True, max_length=160)),
                (
                    "nfct_code",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("origin", models.CharField(default="Nigeria", max_length=80)),
                ("emoji", models.CharField(default="🍽️", max_length=8)),
                ("description", models.TextField(blank=True)),
                ("serving_size", models.CharField(blank=True, max_length=80)),
                ("kcal", models.PositiveIntegerField()),
                ("protein_g", models.FloatField(default=0)),
                ("carbs_g", models.FloatField(default=0)),
                ("fat_g", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FoodTagMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foods.food"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foods.dietarytag",
                    ),
                ),
            ],
            options={
                "unique_together": {("food", "tag")},
            },
        ),
        migrations.AddField(
            model_name="food",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="foods",
                through="foods.FoodTagMap",
                to="foods.dietarytag",
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["name"], name="foods_food_name_8eac09_idx"),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["nfct_code"], name="foods_food_nfct_co_f6fe59_idx"
            ),
        ),
    ]
